version: "3.9"

services:
  db:
    container_name: nexauth_test_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_db_user
      POSTGRES_PASSWORD: test_db_password
    ports:
      - 5433:5432
