export enum NexauthError {
  GET_USER_MALFORMED_AUTHORIZATION_HEADER = 'GET_USER_MALFORMED_AUTHORIZATION_HEADER',
  GET_USER_MISSING_AUTHORIZATION_HEADER = 'GET_USER_MISSING_AUTHORIZATION_HEADER',
  GET_USER_UNVERIFIABLE_AUTHORIZATION_HEADER = 'GET_USER_UNVERIFIABLE_AUTHORIZATION_HEADER',
  LOG_IN_WRONG_EMAIL_OR_PASSWORD = 'LOG_IN_WRONG_EMAIL_OR_PASSWORD',
  SIGN_UP_DUPLICATE_EMAIL = 'SIGN_UP_DUPLICATE_EMAIL',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
}
